 /* Info.obj: */  -u _Fapi_getLibraryInfo
 /* Init.obj: */ -u _Fapi_initializeAPI
 /* FlashStateMachine.obj: */ -u _Fapi_setActiveFlashBank
 /* Async.obj: */ -u _Fapi_issueAsyncCommandWithAddress
 /* BlankCheck.obj: */ -u _Fapi_doBlankCheck
 /* Program.obj: */ -u _Fapi_issueProgrammingCommand
 /* Program.obj: */ -u _Fapi_issueProgrammingCommandForEccAddresses
 /* Verify.obj: */ -u _Fapi_doVerify
 /* Verify.obj: */ -u _Fapi_doVerifyBy16bits
 /* Async.obj: */ -u _Fapi_issueAsyncCommand
 /* FlashStateMachine.obj: */ -u _Fapi_issueFsmSuspendCommand
 /* FlashStateMachine.obj: */ -u _Fapi_checkFsmForReady
 /* FlashStateMachine.obj: */ -u _Fapi_getFsmStatus
 /* Utilities.obj: */ -u _Fapi_calculateEcc
 /* Utilities.obj: */ -u _Fapi_calculateFletcherChecksum
 /* FlashStateMachine.obj: */ -u _Fapi_isAddressEcc
 /* FlashStateMachine.obj: */ -u _Fapi_remapEccAddress
 /* Read.obj: */ -u _Fapi_flushPipeline
 /* Psa.obj: */ -u _Fapi_calculatePsa
 /* Psa.obj: */ -u _Fapi_doPsaVerify
